name: Publish release
on:
  release:
    types: [released]

jobs:
  publish-release:
    name: Publish release
    uses: logikal-io/github-workflows/.github/workflows/publish-release.yml@v1.1.1-dev1
    with:
      name: logikal-docs
    secrets: inherit
